### ISSUE TITLE
Funktioniert leider nicht

### ISSUE THREAD

**Issue by ghost** [Pittini/iobroker-nodemihome#1]
Hey, erstmal danke für die Arbeit. 
Das Skript erkennt zwar den Luftreiniger, zeigt bei den Datenpunkten aber überall 0 an. Wenn man Power ansteuert, kommt leider folgender Fehler: 

```
javascript.0 | 2020-12-08 17:13:58.460 | error | (6923) at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
javascript.0 | 2020-12-08 17:13:58.460 | error | (6923) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
javascript.0 | 2020-12-08 17:13:58.459 | error | (6923) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
javascript.0 | 2020-12-08 17:13:58.458 | error | (6923) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
javascript.0 | 2020-12-08 17:13:58.458 | error | (6923) at Object.<anonymous> (script.js.common.Staubsauger.Luftreiniger:270:25)
javascript.0 | 2020-12-08 17:13:58.457 | error | (6923) at SetDevice (script.js.common.Staubsauger.Luftreiniger:237:30)
javascript.0 | 2020-12-08 17:13:58.456 | error | (6923) script.js.common.Staubsauger.Luftreiniger: TypeError: Cannot read property 'setPower' of undefined
javascript.0 | 2020-12-08 17:13:58.455 | error | (6923) at processImmediate (internal/timers.js:461:21)
javascript.0 | 2020-12-08 17:13:58.454 | error | (6923) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
javascript.0 | 2020-12-08 17:13:58.454 | error | (6923) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
javascript.0 | 2020-12-08 17:13:58.453 | error | (6923) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
javascript.0 | 2020-12-08 17:13:58.453 | error | (6923) at Object.<anonymous> (script.js.common.Staubsauger.Luftreiniger:270:25)
javascript.0 | 2020-12-08 17:13:58.452 | error | (6923) at SetDevice (script.js.common.Staubsauger.Luftreiniger:237:30)
javascript.0 | 2020-12-08 17:13:58.451 | error | (6923) script.js.common.Staubsauger.Luftreiniger: TypeError: Cannot read property 'setPower' of undefined
```

Version 0.1.3 funktioniert allerdings

**Comment by Pittini** [comment]
Komplettes startlog bitte. Und welche Version vom js Adapter?

**Comment by ghost** [comment]
Sorry für die späte Antwort :) Version 4.8.4

Startlog: 
```13.12.2020, 12:31:15.349	[info ]: javascript.0 (918) Stop script script.js.common.Luftreiniger.AirPurifier
13.12.2020, 12:31:15.417	[info ]: javascript.0 (918) Start javascript script.js.common.Luftreiniger.AirPurifier
13.12.2020, 12:31:15.428	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Starting MiHome-Airpurifier3H-V0.1.4
13.12.2020, 12:31:15.428	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching init
13.12.2020, 12:31:15.429	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: registered 0 subscriptions and 0 schedules
13.12.2020, 12:31:15.429	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: You are already logged in, login canceled
13.12.2020, 12:31:15.523	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: CreateStates fertig!
13.12.2020, 12:31:15.523	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching main
13.12.2020, 12:31:15.525	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: {'did':'317235561','token':'aa4f49d6a5004cec29c59b59d49c2d60','longitude':'0.00000000','latitude':'0.00000000','name':'Mi Air Purifier 3/3H','pid':'0','localip':'192.168.0.10','mac':'5C:E5:0C:C6:61:E4','ssid':'RausausmeinerLeitung','bssid':'F4:06:8D:BA:C4:5D','parent_id':'','parent_model':'','show_mode':1,'model':'zhimi.airpurifier.mb3','adminFlag':1,'shareFlag':0,'permitLevel':16,'isOnline':true,'desc':'Device online ','extra':{'isSetPincode':0,'fw_version':'2.0.7','needVerifyCode':0,'isPasswordEncrypt':0,'mcu_version':'0017'},'uid':6258827026,'pd_id':1182,'password':'','p2p_id':'','rssi':-61,'family_id':0,'reset_flag':0}
13.12.2020, 12:31:15.527	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: {'did':'117846133','token':'74614a4d6e4f4c5864356c614b324958','longitude':'0.00000000','latitude':'0.00000000','name':'Klaus','pid':'0','localip':'192.168.0.13','mac':'40:31:3C:A8:D8:FA','ssid':'RausausmeinerLeitung','bssid':'98:9B:CB:99:15:A6','parent_id':'','parent_model':'','show_mode':1,'model':'roborock.vacuum.s5','adminFlag':1,'shareFlag':0,'permitLevel':16,'isOnline':true,'desc':'Fully charged','extra':{'isSetPincode':0,'fw_version':'3.5.7_002008','needVerifyCode':0,'isPasswordEncrypt':0},'event':{'consumable_item_prop_cache':'{\'filter_element_work_time\':\'0\',\'filter_work_time\':\'195188\',\'main_brush_work_time\':\'70568\',\'sensor_dirty_time\':\'70546\',\'side_brush_work_time\':\'397761\'}','event.back_to_dock':'{\'timestamp\':1607778033,\'value\':[0]}','event.back_to_dock_nearby':'{\'timestamp\':1605539807,\'value\':[0]}','event.back_to_dock_no_power':'{\'timestamp\':1592405784,\'value\':[0]}','event.back_to_origin_fail':'{\'timestamp\':1606398535,\'value\':[0]}','event.back_to_origin_succ':'{\'timestamp\':1597768665,\'value\':[0]}','event.bin_full':'{\'timestamp\':1598788801,\'value\':[0]}','event.clean_complete':'{\'timestamp\':1607767046,\'value\':[0]}','event.consume_material_notify':'{\'timestamp\':1604410797,\'value\':[4]}','event.error_code':'{\'timestamp\':1607778033,\'value\':[0]}','event.fan_power_reduced':'{\'timestamp\':1607520856,\'value\':[0]}','event.low_power_back':'{\'timestamp\':1604323630,\'value\':[0]}','event.power_resume_clean':'{\'timestamp\':1591543710,\'value\':[0]}','event.relocate_failed_back':'{\'timestamp\':1579236991,\'value\':[0]}','event.robot_timed_ended':'{\'timestamp\':1607607677,\'value\':[1607607660,0]}','event.robot_timed_started':'{\'timestamp\':1607778001,\'value\':[1607778000,0]}','event.segment_clean_succ':'{\'timestamp\':1604065576,\'value\':[0]}','event.segment_map_done':'{\'timestamp\':1607607762,\'value\':[0]}','event.status':'{\'timestamp\':1607827542,\'value\':[{\'battery\':100,\'clean_area\':140000,\'clean_time\':14,\'dnd_enabled\':0,\'error_code\':0,\'fan_power\':101,\'in_cleaning\':0,\'in_fresh_state\':1,\'in_returning\':0,\'lab_status\':1,\'lock_status\':0,\'map_present\':1,\'map_status\':3,\'msg_seq\':7,\'msg_ver\':3,\'state\':8,\'water_box_status\':0}]}','event.zoned_clean_succ':'{\'timestamp\':1607521480,\'value\':[0]}','prop.battery':'100','prop.fan_power':'101','prop.filter_life':'64','prop.main_brush_life':'94','prop.ota_progress':'100','prop.ota_progress_ts':'1581455195','prop.ota_state':'idle','prop.ota_state_ts':'1607827542','prop.s_mixxx':'{\'StorageKeys_UserSelectedCountryServerCode_117846133_6258827026_MI_3\':\'de\',\'StorageKeys_UserSelectedCountryServerCode_117846133_6395223200_MI_3\':\'de\'}','prop.scene_check_pre_battery':'100','prop.side_brush_life':'45','prop.state':'8'},'uid':6258827026,'pd_id':577,'password':'','p2p_id':'','rssi':-54,'family_id':0,'reset_flag':0}
13.12.2020, 12:31:15.528	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching CreateDpTrigger```

**Comment by Pittini** [comment]
Ok, hab da nen Verdacht. Geh mal bitte mit "suchen und ersetzen" über das Skript, und lass alle vorkommen von 317335021 ersetzen durch 317235561 .Dann bitte nochmal feedback.

**Comment by ghost** [comment]
Also: jetzt zeigt er alle States an (außnahme FilterRemaining), allerdings kann der Modus nicht gewechselt werden (fanlevel, auto, sleep, etc)

Startlog: 

```13.12.2020, 13:24:59.888	[info ]: javascript.0 (918) Start javascript script.js.common.Luftreiniger.AirPurifier
13.12.2020, 13:24:59.892	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Starting MiHome-Airpurifier3H-V0.1.4
13.12.2020, 13:24:59.893	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching init
13.12.2020, 13:24:59.893	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: registered 0 subscriptions and 0 schedules
13.12.2020, 13:24:59.893	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: You are already logged in, login canceled
13.12.2020, 13:24:59.976	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: CreateStates fertig!
13.12.2020, 13:24:59.976	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching main
13.12.2020, 13:24:59.977	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching CreateDevice did=317235561 model=zhimi.airpurifier.mb3 adress=192.168.0.10 token=aa4f49d6a5004cec29c59b59d49c2d60
13.12.2020, 13:24:59.980	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: {'did':'317235561','token':'aa4f49d6a5004cec29c59b59d49c2d60','longitude':'0.00000000','latitude':'0.00000000','name':'Mi Air Purifier 3/3H','pid':'0','localip':'192.168.0.10','mac':'5C:E5:0C:C6:61:E4','ssid':'RausausmeinerLeitung','bssid':'F4:06:8D:BA:C4:5D','parent_id':'','parent_model':'','show_mode':1,'model':'zhimi.airpurifier.mb3','adminFlag':1,'shareFlag':0,'permitLevel':16,'isOnline':true,'desc':'Device online ','extra':{'isSetPincode':0,'fw_version':'2.0.7','needVerifyCode':0,'isPasswordEncrypt':0,'mcu_version':'0017'},'uid':6258827026,'pd_id':1182,'password':'','p2p_id':'','rssi':-61,'family_id':0,'reset_flag':0}
13.12.2020, 13:24:59.984	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: {'did':'117846133','token':'74614a4d6e4f4c5864356c614b324958','longitude':'0.00000000','latitude':'0.00000000','name':'Klaus','pid':'0','localip':'192.168.0.13','mac':'40:31:3C:A8:D8:FA','ssid':'RausausmeinerLeitung','bssid':'98:9B:CB:99:15:A6','parent_id':'','parent_model':'','show_mode':1,'model':'roborock.vacuum.s5','adminFlag':1,'shareFlag':0,'permitLevel':16,'isOnline':true,'desc':'Fully charged','extra':{'isSetPincode':0,'fw_version':'3.5.7_002008','needVerifyCode':0,'isPasswordEncrypt':0},'event':{'consumable_item_prop_cache':'{\'filter_element_work_time\':\'0\',\'filter_work_time\':\'195188\',\'main_brush_work_time\':\'70568\',\'sensor_dirty_time\':\'70546\',\'side_brush_work_time\':\'397761\'}','event.back_to_dock':'{\'timestamp\':1607778033,\'value\':[0]}','event.back_to_dock_nearby':'{\'timestamp\':1605539807,\'value\':[0]}','event.back_to_dock_no_power':'{\'timestamp\':1592405784,\'value\':[0]}','event.back_to_origin_fail':'{\'timestamp\':1606398535,\'value\':[0]}','event.back_to_origin_succ':'{\'timestamp\':1597768665,\'value\':[0]}','event.bin_full':'{\'timestamp\':1598788801,\'value\':[0]}','event.clean_complete':'{\'timestamp\':1607767046,\'value\':[0]}','event.consume_material_notify':'{\'timestamp\':1604410797,\'value\':[4]}','event.error_code':'{\'timestamp\':1607778033,\'value\':[0]}','event.fan_power_reduced':'{\'timestamp\':1607520856,\'value\':[0]}','event.low_power_back':'{\'timestamp\':1604323630,\'value\':[0]}','event.power_resume_clean':'{\'timestamp\':1591543710,\'value\':[0]}','event.relocate_failed_back':'{\'timestamp\':1579236991,\'value\':[0]}','event.robot_timed_ended':'{\'timestamp\':1607607677,\'value\':[1607607660,0]}','event.robot_timed_started':'{\'timestamp\':1607778001,\'value\':[1607778000,0]}','event.segment_clean_succ':'{\'timestamp\':1604065576,\'value\':[0]}','event.segment_map_done':'{\'timestamp\':1607607762,\'value\':[0]}','event.status':'{\'timestamp\':1607827542,\'value\':[{\'battery\':100,\'clean_area\':140000,\'clean_time\':14,\'dnd_enabled\':0,\'error_code\':0,\'fan_power\':101,\'in_cleaning\':0,\'in_fresh_state\':1,\'in_returning\':0,\'lab_status\':1,\'lock_status\':0,\'map_present\':1,\'map_status\':3,\'msg_seq\':7,\'msg_ver\':3,\'state\':8,\'water_box_status\':0}]}','event.zoned_clean_succ':'{\'timestamp\':1607521480,\'value\':[0]}','prop.battery':'100','prop.fan_power':'101','prop.filter_life':'64','prop.main_brush_life':'94','prop.ota_progress':'100','prop.ota_progress_ts':'1581455195','prop.ota_state':'idle','prop.ota_state_ts':'1607827542','prop.s_mixxx':'{\'StorageKeys_UserSelectedCountryServerCode_117846133_6258827026_MI_3\':\'de\',\'StorageKeys_UserSelectedCountryServerCode_117846133_6395223200_MI_3\':\'de\'}','prop.scene_check_pre_battery':'100','prop.side_brush_life':'45','prop.state':'8'},'uid':6258827026,'pd_id':577,'password':'','p2p_id':'','rssi':-54,'family_id':0,'reset_flag':0}
13.12.2020, 13:24:59.984	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching CreateDpTrigger
13.12.2020, 13:25:00.394	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: Reaching RefreshDps 
13.12.2020, 13:25:00.396	[info ]: javascript.0 (918) script.js.common.Luftreiniger.AirPurifier: [true,'none',1,false,2,21,48,1,0]´´´

Log beim ansteuern:

```javascript.0 | 2020-12-13 13:28:51.233 | error | (918) at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
javascript.0 | 2020-12-13 13:28:51.233 | error | (918) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
javascript.0 | 2020-12-13 13:28:51.233 | error | (918) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
javascript.0 | 2020-12-13 13:28:51.232 | error | (918) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
javascript.0 | 2020-12-13 13:28:51.232 | error | (918) at Object.<anonymous> (script.js.common.Luftreiniger.AirPurifier:266:25)
javascript.0 | 2020-12-13 13:28:51.232 | error | (918) at SetDevice (script.js.common.Luftreiniger.AirPurifier:236:30)
javascript.0 | 2020-12-13 13:28:51.231 | error | (918) at module.exports.setMode (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/zhimi.airpurifier.mb3.js:85:17)
javascript.0 | 2020-12-13 13:28:51.231 | error | (918) at module.exports.miotSetProperty (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:162:13)
javascript.0 | 2020-12-13 13:28:51.231 | error | (918) script.js.common.Luftreiniger.AirPurifier: Error: Property set_mode is not define
javascript.0 | 2020-12-13 13:28:51.229 | error | (918) at processImmediate (internal/timers.js:461:21)
javascript.0 | 2020-12-13 13:28:51.229 | error | (918) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
javascript.0 | 2020-12-13 13:28:51.229 | error | (918) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
javascript.0 | 2020-12-13 13:28:51.228 | error | (918) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
javascript.0 | 2020-12-13 13:28:51.228 | error | (918) at Object.<anonymous> (script.js.common.Luftreiniger.AirPurifier:266:25)
javascript.0 | 2020-12-13 13:28:51.228 | error | (918) at SetDevice (script.js.common.Luftreiniger.AirPurifier:236:30)
javascript.0 | 2020-12-13 13:28:51.227 | error | (918) at module.exports.setMode (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/zhimi.airpurifier.mb3.js:85:17)
javascript.0 | 2020-12-13 13:28:51.227 | error | (918) at module.exports.miotSetProperty (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:162:13)
javascript.0 | 2020-12-13 13:28:51.226 | error | (918) script.js.common.Luftreiniger.AirPurifier: Error: Property set_mode is not define```

**Comment by Pittini** [comment]
> Also: jetzt zeigt er alle States an (außnahme FilterRemaining), allerdings kann der Modus nicht gewechselt werden (fanlevel, auto, sleep, etc)

Jap, dafür kann ich nix, siehe readme, Known Issues.

Kommt jetzt drauf an wie fit Du bist, ich kann Dir sagen wie Du das Problem lokal lösen kannst bis der node-mihome Entwickler meinen pull request mal ausführt.

Du mußt letztendlich nur eine Datei austauschen, und zwar die  zhimi.airpurifier.mb3.js  im Verzeichnis "/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/" mit der korrigierten Version meiner Fork: https://github.com/Pittini/node-mihome/blob/master/lib/devices/zhimi.airpurifier.mb3.js

Ob Du lieber die Datei oder den Inhalt tauschst is letzlich egal und Dir überlassen. Nach dem Tausch und neustart des js Controllers sind die beiden von Dir genannten Probleme dann weg.

**Comment by ghost** [comment]
Ein Traum, vielen Dank!

**Comment by ghost** [comment]
Hallo Nochmals, 

da der angegebene Pfad "/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/" nicht existiert, sehr wohl aber "/opt/iobroker/node_modules/node-mihome/lib/devices/" habe ich die Datei darin geändert. leider hat das keine Abhilfe geschaffen.

 Noch ein Tipp?

**Comment by Pittini** [comment]
> Hallo Nochmals,
> 
> da der angegebene Pfad "/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/devices/" nicht existiert, sehr wohl aber "/opt/iobroker/node_modules/node-mihome/lib/devices/" habe ich die Datei darin geändert. leider hat das keine Abhilfe geschaffen.
> 
> Noch ein Tipp?

Du mußt nach jeder Änderung der Datei den JS Adapter neustarten das er das einliest. Das der Pfad bei Dir so nicht existiert is seltsam, aber da hab ich zuwenig Plan von Linux um das ergründen zu können, alle anderen hatten die Datei dort wo ich angegeben hatte.

**Comment by ghost** [comment]
hm, komisch. Neugestartet wurde er natürlich. Dann warte ich mal denn pull ab. Trotzdem danke!

**Comment by pinoxl** [comment]
Hallo guten Abends, gibt es  was für Mi Air Purifier 3C 
Ich wäre für jede Hilfe dankbar

**Comment by Pittini** [comment]
> Hallo guten Abends, gibt es was für Mi Air Purifier 3C
> Ich wäre für jede Hilfe dankbar

Aktuell nicht unterstützt, denk aber ist integrierbar. Wird aber noch etwas dauern, Modelle einpflegen kommt nach Code fertigstellen.

**Comment by pinoxl** [comment]
Viele danke Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Pittini <notifications@github.com> Datum: 30.12.20  19:28  (GMT+01:00) An: Pittini/iobroker-nodemihome <iobroker-nodemihome@noreply.github.com> Cc: pinoxl <pinoxl@t-online.de>, Comment <comment@noreply.github.com> Betreff: Re: [Pittini/iobroker-nodemihome] Funktioniert leider nicht (#1) 



Hallo guten Abends, gibt es was für Mi Air Purifier 3C

Ich wäre für jede Hilfe dankbar



Aktuell nicht unterstützt, denk aber ist integrierbar. Wird aber noch etwas dauern, Modelle einpflegen kommt nach Code fertigstellen.

**Comment by pinoxl** [comment]
Danke :-)
