### ISSUE TITLE
You are assigning a number to the state "javascript.0.MiHomeAll.78328901.rgb" which expects a string.

### ISSUE THREAD

**Issue by Grothesk242** [Pittini/iobroker-nodemihome#23]
Script version 0.2.11 (from the header / git says 0.2.12?) 
I get following warnings: 

```
2021-04-23 11:46:21.269  - warn: javascript.0 (4449) You are assigning a number to the state "javascript.0.MiHomeAll.78328901.rgb" which expects a string. Please fix your code to use a string or change the state type to number. This warning might become an error in future versions.
2021-04-23 11:46:21.279  - warn: javascript.0 (4449)     at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1427:20)
2021-04-23 11:46:21.280  - warn: javascript.0 (4449)     at RefreshDps (script.js.common.nodemi:705:45)
2021-04-23 11:46:21.280  - warn: javascript.0 (4449)     at module.exports.<anonymous> (script.js.common.nodemi:658:21)
2021-04-23 11:46:21.280  - warn: javascript.0 (4449)     at module.exports.emit (node:events:365:28)
2021-04-23 11:46:21.281  - warn: javascript.0 (4449)     at module.exports.emit (node:domain:470:12)
2021-04-23 11:46:21.281  - warn: javascript.0 (4449)     at module.exports.loadProperties (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:107:12)

```

**Comment by Pittini** [comment]
Exact Modelname please. You found it in the Info Channel. And....read known Issues.

**Comment by Grothesk242** [comment]
This is 
lumi.gateway.v3

Okay, known issue. Sorry for posting.

**Comment by Pittini** [comment]
The Gateway is NOT supportet, its just integrated for testing internally. Ignore it.
