### ISSUE TITLE
Fan 2S reagiert nicht auf Stateänderungen / Fehlermeldungen beim Start des Scripts

### ISSUE THREAD

**Issue by TepMan** [Pittini/iobroker-nodemihome#32]
Hi,

ich probiere gerade, meinen 2S Fan mit dem Script zu steuern. Leider klappt das nicht. Wenn ich einen State ändere, quittiert der Fan das zwar mit einem Piep, es passiert aber nichts. Ausserdem sind mir folgende Warnings beim Script-Start aufgefallen:

`

2021-06-11 17:29:35.590 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Retrieving your in de registered MiHome Devices
--
2021-06-11 17:29:36.182 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Found 1 MiHome Devices, those are:
2021-06-11 17:29:36.183 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Ventilator
2021-06-11 17:29:36.184 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Now searching for supported Devices...
2021-06-11 17:29:36.184 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Device Ventilator is supported, creating DataPoints
2021-06-11 17:29:36.199 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Now creating device for zhimi.fan.za4 / 393896806 / 192.168.178.55 / 879480a72b00393da32b8409511c7d0e / 10000
2021-06-11 17:29:36.201 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Created device {"_events":{},"_eventsCount":0,"_maxListeners":100,"id":"393896806","address":"192.168.178.55","token":"879480a72b00393da32b8409511c7d0e","protocol":"local","refresh":10000,"_properties":{},"_propertiesToMonitor":["power","angle","angle_enable","speed_level","natural_level","child_lock","poweroff_time","buzzer","led_b"],"_miotSpec":null,"_miotSpecType":null,"model":"zhimi.fan.za4","setter":{},"definition":{"info":[{"id":"localip","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Ip Adress","type":"string","role":"value","def":""}},{"id":"token","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Token","type":"string","role":"value","def":""}},{"id":"did","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Device Id","type":"string","role":"value","def":""}},{"id":"model","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Model","type":"string","role":"value","def":""}},{"id":"rssi","initial":0,"forceCreation":false,"common":{"read":true,"write":false,"name":"rssi","type":"number","role":"value.rssi","def":0}},{"id":"name","initial":"","forceCreation":false,"common":{"read":true,"write":true,"name":"Name","type":"string","role":"value","def":""}},{"id":"isOnline","initial":false,"forceCreation":false,"common":{"read":true,"write":true,"name":"Is online","type":"boolean","role":"value","def":false}}],"model":"zhimi.fan.za4","description":"Fan","setter":{},"common":[{"name":"power","type":"boolean","role":"switch","read":true,"write":true},{"name":"angle","type":"number","read":true,"write":true,"min":1,"max":120,"role":"state"},{"name":"angle_enable","type":"boolean","role":"switch","read":true,"write":true},{"name":"fan_level","type":"number","read":true,"write":true,"min":1,"max":4,"role":"state"},{"name":"buzzer","type":"boolean","role":"switch","read":true,"write":true},{"name":"child_lock","type":"boolean","role":"switch","read":true,"write":true},{"name":"led_b","type":"boolean","role":"switch","read":true,"write":true},{"name":"speed_level","type":"number","read":true,"write":true,"min":1,"max":4,"role":"state"},{"name":"poweroff_time","type":"number","read":true,"write":true,"min":0,"max":540,"unit":"m","role":"state"}]},"firstrun":true} now fetching data
2021-06-11 17:29:36.623 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Init Device# 0 - device="zhimi.fan.za4"
2021-06-11 17:29:36.624 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Setting trigger #0 for zhimi.fan.za4
2021-06-11 17:29:46.885 -&nbsp;warn: javascript.0 (4154) You are assigning a number to the state "javascript.0.MiHomeAll.393896806.buzzer" which expects a boolean. Please fix your code to use a boolean or change the state type to number. This warning might become an error in future versions.
2021-06-11 17:29:46.944 -&nbsp;warn: javascript.0 (4154) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1427:20)
2021-06-11 17:29:46.947 -&nbsp;warn: javascript.0 (4154) at RefreshDps (script.js.common.Hardware.AllMyMi:690:45)
2021-06-11 17:29:46.948 -&nbsp;warn: javascript.0 (4154) at module.exports.&nbsp;(script.js.common.Hardware.AllMyMi:643:21)
2021-06-11 17:29:46.948 -&nbsp;warn: javascript.0 (4154) at module.exports.emit (events.js:314:20)
2021-06-11 17:29:46.949 -&nbsp;warn: javascript.0 (4154) at module.exports.EventEmitter.emit (domain.js:483:12)
2021-06-11 17:29:46.949 -&nbsp;warn: javascript.0 (4154) at module.exports.loadProperties (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:107:12)
2021-06-11 17:29:46.950 -&nbsp;warn: javascript.0 (4154) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:73:9)
2021-06-11 17:29:46.951 -&nbsp;warn: javascript.0 (4154) You are assigning a number to the state "javascript.0.MiHomeAll.393896806.led_b" which expects a boolean. Please fix your code to use a boolean or change the state type to number. This warning might become an error in future versions.
2021-06-11 17:29:46.953 -&nbsp;warn: javascript.0 (4154) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1427:20)
2021-06-11 17:29:46.954 -&nbsp;warn: javascript.0 (4154) at RefreshDps (script.js.common.Hardware.AllMyMi:690:45)
2021-06-11 17:29:46.954 -&nbsp;warn: javascript.0 (4154) at module.exports.&nbsp;(script.js.common.Hardware.AllMyMi:643:21)
2021-06-11 17:29:46.955 -&nbsp;warn: javascript.0 (4154) at module.exports.emit (events.js:314:20)
2021-06-11 17:29:46.955 -&nbsp;warn: javascript.0 (4154) at module.exports.EventEmitter.emit (domain.js:483:12)
2021-06-11 17:29:46.956 -&nbsp;warn: javascript.0 (4154) at module.exports.loadProperties (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:107:12)
2021-06-11 17:29:46.956 -&nbsp;warn: javascript.0 (4154) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:73:9)
2021-06-11 17:31:34.182 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Keyvalue=false key=0
2021-06-11 17:31:34.185 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: {}
2021-06-11 17:31:49.562 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Keyvalue=true key=0
2021-06-11 17:31:49.563 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: {}
2021-06-11 17:32:29.117 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: Keyvalue=1 key=7
2021-06-11 17:32:29.119 -&nbsp;info: javascript.0 (4154) script.js.common.Hardware.AllMyMi: {}

`

Hat das vielleicht miteinander zu tun?

**Comment by TepMan** [comment]
Sorry, habe versehentlich eine alte Version verwendet.
