### ISSUE TITLE
Error: network timeout at: https://api.io.mi.com/app/home/device_list

### ISSUE THREAD

**Issue by Grothesk242** [Pittini/iobroker-nodemihome#61]
Hat sich bei der URL was getan? 
Das skript bemängelt: 

````
2022-07-22 19:05:42.199  - info: javascript.0 (155217) Start javascript script.js.common.nodemihome
2022-07-22 19:05:42.394  - info: javascript.0 (155217) script.js.common.nodemihome: Starting AllMyMi V.0.2.29
2022-07-22 19:05:42.500  - info: javascript.0 (155217) script.js.common.nodemihome: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
2022-07-22 19:05:43.259  - info: javascript.0 (155217) script.js.common.nodemihome: Retrieving your in cn registered MiHome Devices
2022-07-22 19:05:48.288  - error: javascript.0 (155217) An error happened which is most likely from one of your scripts, but the originating script could not be detected.
2022-07-22 19:05:48.290  - error: javascript.0 (155217) Error: network timeout at: https://api.io.mi.com/app/home/device_list
2022-07-22 19:05:48.291  - error: javascript.0 (155217) FetchError: network timeout at: https://api.io.mi.com/app/home/device_list
    at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-fetch/lib/index.js:1484:13)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```

**Comment by Pittini** [comment]
Nein hat sich nix geändert, läuft bei mir auch nach wie vor einwandfrei. Hast iwas upgedated oder geändert? Wenn nein, mal komplett neustarten und oder bissl warten, gab schon mal vor längerem son komischen Effekt wo bei x Leuten nix mehr ging und am nächsten Tag war wieder alles paletti.

**Comment by Grothesk242** [comment]
Ja, ich habe gerade noch was getestet. Mit
 javascript     - v5.7.0
funktioniert das log in, mit 
 javascript     - v6.0.0
nicht mehr. 
Aber was sich da geändert hat... K.A. :-D

**Comment by Grothesk242** [comment]
Aber wo ich dich gerade am Rohr hab... 
Unter javascript 5.7.0 wird das bekrittelt: 

```
2022-07-22 19:49:41.466  - info: javascript.0 (158451) script.js.common.nodemihome: Init Device# 0 - device="lumi.gateway.v3"
2022-07-22 19:49:41.467  - info: javascript.0 (158451) script.js.common.nodemihome: Setting trigger #0 for lumi.gateway.v3
2022-07-22 19:49:51.477  - warn: javascript.0 (158451) You are assigning a number to the state "javascript.0.MiHomeAll.78328901.rgb" which expects a string. Please fix your code to use a string or change the state type to number. This warning might become an error in future versions.
2022-07-22 19:49:51.493  - warn: javascript.0 (158451)     at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1532:20)
2022-07-22 19:49:51.495  - warn: javascript.0 (158451)     at RefreshDps (script.js.common.nodemihome:1016:37)
2022-07-22 19:49:51.495  - warn: javascript.0 (158451)     at module.exports.<anonymous> (script.js.common.nodemihome:940:21)
2022-07-22 19:49:51.495  - warn: javascript.0 (158451)     at module.exports.emit (node:events:513:28)
2022-07-22 19:49:51.496  - warn: javascript.0 (158451)     at module.exports.emit (node:domain:482:12)
2022-07-22 19:49:51.496  - warn: javascript.0 (158451)     at module.exports.loadProperties (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/device-miio.js:107:12)
2022-07-22 19:49:51.515  - info: javascript.0 (158451) State value to set for "javascript.0.MiHomeAll.78328901.rgb" has to be type "string" but received type "number"
```

**Comment by ghost** [comment]
Gleiches Problem bei mir gerade nach einer frischen Installation, nur lässt sich das auch nicht fixen durch ein Downgrade auf JS v5.7.0. Irgendeine Idee was ich testen könnte? Mein (einziges) device wird mir in meiner in den objects angezeigt inkl aktueller Daten von wie Local IP etc., alle eigentlichen Aktionen jedoch auf (null). Das entsprechende File habe ich rüber kopiert und auch mehrmals neugestartet. Irgendwelche Ideen was ich tun könnte?

Edit: Bei Änderungen an irgendeinem der (null) states wie Power, Level etc. bekomme ich dann auch Timeouts im Log:
```
2022-08-19 23:40:13.027 - info: javascript.0 (2930) script.js.MiHome: Keyvalue=true key=0
2022-08-19 23:40:13.029 - info: javascript.0 (2930) script.js.MiHome: {}
2022-08-19 23:40:13.765 - error: javascript.0 (2930) An error happened which is most likely from one of your scripts, but the originating script could not be detected.
2022-08-19 23:40:13.767 - error: javascript.0 (2930) Error: Call to device timed out
2022-08-19 23:40:13.768 - error: javascript.0 (2930) Error: Call to device timed out
at Timeout.retry [as _onTimeout] (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib/protocol-miio.js:358:23)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
```

**Comment by dft601** [comment]
Habe auch ein Timeout-Problem:

<html>
<body>


javascript.0 | 2022-10-04 12:37:11.903 | error | FetchError: network timeout at: https://de.api.io.mi.com/app/home/device_list at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-fetch/lib/index.js:1484:13) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
-- | -- | -- | --
javascript.0 | 2022-10-04 12:37:11.903 | error | Error: network timeout at: https://de.api.io.mi.com/app/home/device_list
javascript.0 | 2022-10-04 12:37:11.902 | error | An error happened which is most likely from one of your scripts, but the originating script could not be detected.


</body>
</html>

**Comment by George-Cara** [comment]
Hi . For this error with newer JSCRIPT Adapter (>6) the developer should modify the code. until then please go to /opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/lib and edit the file protocol-micloud.js . You will find 
this.REQUEST_TIMEOUT = that you should set to 20000
This is the proper timeout for me. I think it will work for you also.

**Comment by dft601** [comment]
> 

MY HERO. Thanks... After more than a half year I can use it again.
